### PR TITLE
kubevirt_vm: Prevent unnecessary whitespace

### PR DESCRIPTION
**Pull request by 0xFelix**
**What this PR does / why we need it**:

This removes the unnecessary whitespace from the rendered VirtualMachine
template and adds a unit test for it.

**Special notes for your reviewer**:

Merge after #4

**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by jcanocan** [comment]
Could it also happen that white spaces appear on the right?

**Comment by 0xFelix** [comment]
@jcanocan It could happen, that is up to the user input. But without this change rendering the template would produce an extra newline every time.

**Comment by jcanocan** [comment]
> @jcanocan It could happen, that is up to the user input. But without this change rendering the template would produce an extra newline every time.

I see. Thanks for the explanation!

**Pull request merged**
